name: Android CI

on:
  push:
    branches: [ "master", "v*" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./studio-android/LightNovelLibrary

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up Android emulator, build, test and Coveralls
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 21
        arch: x86_64
        profile: Nexus 6
        working-directory: ./studio-android/LightNovelLibrary
        # script: ./gradlew assembleAlpha connectedAlphaDebugAndroidTest coveralls
        script: ./gradlew assembleAlpha connectedAlphaDebugAndroidTest
