name: Android CI

on:
  push:
    branches: [ "master", "v*" ]
  pull_request:
    branches: [ "master" ]

env:
  TARGET_SDK_VERSION: 29
  BUILD_TOOLS_VERSION: 29.0.3

defaults:
  run:
    working-directory: ./studio-android/LightNovelLibrary

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up Android emulator, build, test and Coveralls
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: cd ./studio-android/LightNovelLibrary && ./gradlew assembleAlpha connectedAlphaDebugAndroidTest coveralls

